### ISSUE TITLE
Where is ofxVideoFrame.h?

### ISSUE THREAD

**Issue by bakercp** [bakercp/ofxVideoBuffer#1]
In ofxVideoBufferData.h ofxVideoFrame.h is included but the compiler can't find the file.

**Comment by bakercp** [comment]
I just updated the read me on this -- I refactored a few common video items into https://github.com/bakercp/ofxVideoUtils.  You will find the missing file there now.

**Comment by gilfuser** [comment]
Hi
I know this is really old stuff. But I'm trying to build he example and I'm having this same issue.
( + identifier "ofxSharedVideoFrame" is undefined )
I googled to see if I could find were ofxVideoFrame.h lives, but I got no luck.
I'm pretty a newbie on all of this. Maybe I should have been using something newer.
Do you have any suggestion?

thanks

bests,
Gil
